permissions:
  gametemplate-admin: "gametemplate.admin"

locations:
  lobby:
    world: "World"
    x: 12
    y: 12
    z: 12

  game:
    world: "World"
    x: 12
    y: 12
    z: 12

messages:
  prefix: "&3&lGame&b&lTemplate &8┃"
  no-permission: "%prefix% &7You cant access this command."
  user:
    game-started: "%prefix% &7The game has &a&lSTARTED&7."
    game-ended: "%prefix% &7The game has &c&lENDED&7."
    game-restarting: "%prefix% &7The game is &e&lRESTARTING&7."
  admin:
    game-menu:
      - ""
      - " &3&lGame&b&lTemplate &7(Shows all useful commands)"
      - ""
      - " &8- &b/gametemplate reload &7(Reloads the configuration)"
      - " &8- &b/gametemplate setlobby &7(Sets the lobby)"
      - " &8- &b/gametemplate setspawn &7(Sets the game spawn)"
      - ""
    set-game-spawn: "%prefix% &7You have set the &b&lGAME SPAWN&7."
    set-lobby-spawn: "%prefix% &7You have set the &b&lLOBBY SPAWN&7."
    reloaded-config: "%prefix% &7You have &a&lRELOADED &7the configuration."
