permissions:
  gametemplate-admin: "gametemplate.admin"

locations:
  lobby:
    world: "World"
    x: 12
    y: 12
    z: 12
  game:
    world: "World"
    x: 12
    y: 12
    z: 12

messages:
  prefix: "&3&lGame&b&lTemplate &8┃"
  no-permission: "%prefix% &7You cant access this command."
  user:
    game-started: "%prefix% &7The game has &a&lSTARTED&7."
    game-ended: "%prefix% &7The game has &c&lENDED&7."
    game-restarting: "%prefix% &7The game is &e&lRESTARTING&7."

  admin:
